name: Install Yarn and dependencies
on: [workflow_call]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Initialize Yarn and install package dependencies
        run: yarn & yarn install
