name: "[point-utilities] Jest unit tests"
on: [pull_request]
jobs:
  install:
    uses: ./.github/workflows/install.yml
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Run tests
        run: cd packages/point-utilities && yarn test